FROM rh-registry.gazprom-neft.local:5000/ubi8/nodejs-12 as build

LABEL vendor="GROTEM" \
      author="Gennadii Sychev" \
      author-email="gusychev@grotem.com"

WORKDIR /opt/app-root/src
COPY . .

ENV TZ="Europe/Moscow" \
    API="https://gateways-mercapp.apps.test.gazprom-neft.local" \
    SSO="https://sso-mercapp.apps.test.gazprom-neft.local" \
    PROD="true"
    
RUN npm install --registry=http://nexus.gazprom-neft.local:8080/repository/npm-nodejs-external-dso/
RUN npm run "build gpn-oil-lib"
RUN npm run "build webmarketing"

FROM rh-registry.gazprom-neft.local:5000/rhel8/nginx-116
COPY --from=build /opt/app-root/src/dist/webmarketing /usr/share/nginx/html
COPY nginx.conf /etc/nginx/
CMD ["nginx", "-g", "daemon off;"]