apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName | trunc 63 }}
  labels:
    {{- toYaml .Values.appLabels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name | trunc 63 }}
  selector:
    {{- toYaml .Values.appLabels | nindent 4 }}
