---
- name: install
  hosts: hostname
  become: yes

  tasks:
  - yum:
     update_cache: yes
     name: "{{item}}"
     state: latest
    loop:
     - yum-utils
     - device-mapper-persistent-data
     - lvm2
     - libcgroup-tools

  - shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    args:
     executable: /bin/bash

  - yum:
     name: "{{item}}"
     state: latest
    loop:
     - docker-ce
     - docker-ce-cli
     - containerd.io

  - systemd:
      name: docker
      state: started
      enabled: yes