---
- name: install
  hosts: hostname
  become: yes

  tasks:
  - name: Add repository
    yum_repository:
     name: grafana
     description: grafana
     baseurl: https://packages.grafana.com/oss/rpm
     gpgkey: https://packages.grafana.com/gpg.key
     sslverify: yes
     sslcacert: /etc/pki/tls/certs/ca-bundle.crt
     gpgcheck: yes
     repo_gpgcheck: yes
     enabled: yes
     state: present

  - yum:
     name: https://dl.grafana.com/oss/release/grafana-7.5.10-1.x86_64.rpm
     state: present

  - firewalld:
      port: 3000/tcp
      permanent: yes
      immediate: yes
      state: enabled

  - name: Install
    grafana_plugin:
     name: alexanderzobnin-zabbix-app
     version: 4.1.2
     state: present

  - name: start
    systemd:
      state: started
      daemon_reload: yes
      name: grafana-server
      enabled: yes