---
apiVersion: v1
kind: Secret
metadata:
  name: mi
  labels:
    app.kubernetes.io/name: mi
    app.kubernetes.io/instance: mi
type: Opaque
stringData:
  user: "admin"
  password: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mi-headless
  labels:
    app.kubernetes.io/name: mi
    app.kubernetes.io/instance: mi
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: minio
      port: 9000
      targetPort: minio
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mi
    app.kubernetes.io/instance: mi
---
apiVersion: v1
kind: Service
metadata:
  name: mi
  labels:
    app.kubernetes.io/name: mi
    app.kubernetes.io/instance: mi
spec:
  type: ClusterIP
  ports:
    - name: minio
      port: 9000
      targetPort: minio
  selector:
    app.kubernetes.io/name: mi
    app.kubernetes.io/instance: mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mi
  labels:
    app.kubernetes.io/name: mi
    app.kubernetes.io/instance: mi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mi
      app.kubernetes.io/instance: mi
  serviceName: mi-headless
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mi
        app.kubernetes.io/instance: mi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/minio/v2/metrics/cluster"
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: minio
          image: quay.io/bitnami/minio:2021.6.17-debian-10-r14
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MINIO_SCHEME
              value: "http"
            - name: MINIO_FORCE_NEW_KEYS
              value: "no"
            - name: MINIO_SKIP_CLIENT
              value: "yes"
            - name: MINIO_BROWSER
              value: "off"
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
            - name: MINIO_ROOT_USER # MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mi
                  key: user
            - name: MINIO_ROOT_PASSWORD # MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mi
                  key: password
          ports:
            - name: minio
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: minio
              scheme: "HTTP"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: minio
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - mountPath: /data
              name: data  
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "managed-nfs-storage"
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    name: console
spec:
  ports:
    - port: 9090
      name: http
    - port: 9443
      name: https
  selector:
    app: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: minio/console:v0.10.3
          imagePullPolicy: "IfNotPresent"
          args:
            - server
          ports:
            - containerPort: 9090
              name: http
          env:
            - name: CONSOLE_MINIO_SERVER
              value: "http://mi:9000"
            - name: CONSOLE_PORT
              value: "9090"